linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/namecoin)
  goimports:
    local-prefixes: "github.com/namecoin"
  gomoddirectives:
    replace-local: true
    replace-allow-list:
      - "github.com/namecoin/x509-compressed"
      - "github.com/coreos/go-systemd"
  varnamelen:
    ignore-type-assert-ok: true
